### ISSUE TITLE
Two EdgeBars in one addin

### ISSUE THREAD

**Issue by michalzemek** [SolidEdgeCommunity/SolidEdge.Community.AddIn#5]
Hello,
I am trying to create an addin with two different edge bars. But only the edge bar, which is added as second, is shown in Solid edge. The first one is just not there. I tried that also with the TestAddIn, which is in the SolidEdge.CommunityAddIn project. I have added MyEdgeBarControl and MyEdgeBarControl2 like this:

```
        public override void OnCreateEdgeBarPage(EdgeBarController controller, SolidEdgeFramework.SolidEdgeDocument document)
       {            
            controller.Add<MyEdgeBarControl>(document, 107);
            controller.Add<MyEdgeBarControl2>(document, 100);
        }
```

Again, only the MyEdgeBarControl2 is shown and icons are mixed up. Some of them are from the MyEdgeBarControl2, some of them from the MyEdgeBarControl.
Is it a bug, or does SolidEdge support only one EdgeBar per an addin? Any help would be deeply appreciated.
Thanks,
Michal

**Comment by jlnewell** [comment]
I emailed a SE developer for clarification. I'm still not 100% certain that I understand what he said but I will be testing this functionality this week.

**Comment by michalzemek** [comment]
Thank you very much, I am looking forward for the result.

**Comment by jlnewell** [comment]
I got feedback from development. I have tested their suggestions but I am yet to get it to work with 2 EdgeBar pages. A lot of people are asking for this so I won't forget about it or stop trying. I'll followup when I know more.

**Comment by michalzemek** [comment]
Thank you, I appreciate it.

**Comment by jlnewell** [comment]
Got it working. I just released an alpha NuGet package for you to test with. Give it a shot and let me know. https://www.nuget.org/packages/SolidEdge.Community.AddIn/109.0.0-alpha1

**Comment by michalzemek** [comment]
Hi,
thanks for the update. I have tested it. It works fine if I open one document (then both edge bars are visible.). But I think there is still an issue if more documents are open one by one. And the behavior is different for parts and assemblies. Here are my results:
first asm doc - ok, both edge bars are visible
second asm doc - ok, both edge bars are visible
**third asm doc - no edge bar
fourth asm doc - no edge bar**
-----------------
first part doc - ok, both edge bars are visible 
second part doc - ok, both edge bars are visible 
**third part doc - only the second edge bar is visible**
fourth part doc - ok, both edge bars are visible

Could you check this? Thank you.

**Comment by oggiepl** [comment]
Hi guys,
any progress on this issue?

**Comment by metalixyaron** [comment]
@jlnewell, hi, I also encountered with similar problem. I tested the alpha ver and managed to get both edgebars in the demo addin.
The problem I had is that when I try to replace the edgebar page in a specific doc (by removing all prev pages and inserting the new one), I can see the new bar only after manually resizing the panel.
